### ISSUE TITLE
aws-otel-collector container stopping due to deprecation errors

### ISSUE THREAD

**Issue by henriquesantanati** [aws-containers/ecsworkshop#65]
The workshop [CONFIGURE AMAZON MANAGED SERVICE FOR PROMETHEUS / GRAFANA FOR YOUR ECS CLUSTER](https://www.ecsworkshop.com/monitoring/amp_amg/) is not showing metrics under Grafana dashboard.

Checking the ECS Task, I realised that the `aws-otel-collector` container was being stopped with `exit code 1`. Looking at the logs, I've seen these 2 errors below:

`Error: failed to get config: cannot unmarshal the configuration: unknown exporters type "awsprometheusremotewrite" for "awsprometheusremotewrite" (valid values: [awsxray awsemf signalfx datadog otlphttp logzio logging otlp prometheusremotewrite prometheus file dynatrace sapm])`

`2022/11/02 11:59:43 application run finished with error: failed to get config: cannot unmarshal the configuration: error reading processors configuration for "metricstransform": 10 error(s) decoding:  'transforms[*]' has invalid keys: metric_name`

Both erros are related to Open-telemetry deprecations as per below:

* [Remove deprecated metric_name setting #12737](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/12737) - It was replaced by `include` as per [the docs](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/metricstransformprocessor)
* [awsprometheusremotewriteexporter deprecation notice](https://pkg.go.dev/github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsprometheusremotewriteexporter#section-readme) - Users who want to send metrics to Amazon Managed Service for Prometheus will need to instead use the [Prometheus Remote Write Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusremotewriteexporter/README.md) along with the [Sigv4 Authenticator Extension](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/sigv4authextension/README.md) to achieve the same result.

That all said, I'm opening a PR with the fixes for the above.

**Comment by henriquesantanati** [comment]
PR opened on [ECS Demo Amp repository](https://github.com/aws-samples/ecsdemo-amp/pull/4).

**Comment by maishsk** [comment]
Fixed with https://github.com/aws-samples/ecsdemo-amp/pull/4
