### ISSUE TITLE
An error occurred (AccessDenied) when calling the AssumeRole operation: User

### ISSUE THREAD

**Issue by quezon** [aws-containers/ecsworkshop#66]
After running any of these commands: 
`
aws iam get-role --role-name "AWSServiceRoleForElasticLoadBalancing" || aws iam create-service-linked-role --aws-service-name "elasticloadbalancing.amazonaws.com"

aws iam get-role --role-name "AWSServiceRoleForECS" || aws iam create-service-linked-role --aws-service-name "ecs.amazonaws.com"
`
I get this error message:
**An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::350514568196:assumed-role/ecsworkshop-admin/i-03a0645e089123f6f is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::350514568196:role/ecsworkshop-admin**

Which steps I need to do in order to fix this issue?

**Comment by maishsk** [comment]
This was as a result of the change in the way IAM  role trust policy behavior
https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/

This has been addressed by #71
